name: Wheels

on: workflow_call

permissions:
  contents: read

jobs:
  wheels_lint:
    uses: ./.github/workflows/ruff.yml
  wheels_mypy:
    uses: ./.github/workflows/mypy.yml
  build_wheels:
    name: Build wheel
    needs: [wheels_lint, wheels_mypy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Build wheel
        run: pipx run build --wheel

      - uses: actions/upload-artifact@v7
        with:
          name: ripleypy-wheels
          path: dist/*.whl

  build_sdist:
    name: Build source distribution
    needs: [wheels_lint, wheels_mypy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v7
        with:
          name: ripleypy-sdist
          path: dist/*.tar.gz