name: Wheels

on: workflow_call

jobs:
  wheels_lint:
    uses: ./.github/workflows/ruff.yml
  wheels_mypy:
    uses: ./.github/workflows/mypy.yml
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    needs: [wheels_lint, wheels_mypy]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v7

      - name: Build wheels
        run: python -m pip wheel -w wheelhouse .

      - uses: actions/upload-artifact@v7
        with:
          name: pyripley-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    needs: [wheels_lint, wheels_mypy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v7
        with:
          name: pyripley-sdist
          path: dist/*.tar.gz